[package]
name = "libtext"
version = "0.1.0"
edition = "2024"

[lib]
name = "libtext"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version="0.24.2", features=["extension-module"] }
unicode-width = "0.1"